package Views;

import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Rebecca Broughton
 */
public class TheFrame extends javax.swing.JFrame {
  
  public JMenu getfileMenu(){
    return fileMenu;
  }
  
  public JMenuItem getOpenMenuItem(){
    return open;
  }
  
  public JMenuItem getNewMenuItem(){
    return New;
  }
  
  public JMenuItem getSaveMenuItem(){
    return Save;
  }
  
  public JMenuItem getSaveAsMenuItem(){
    return SaveAs;
  }
  
  public JTextArea getTextArea(){
    return mainTextArea;
  }
  
  public JTextField getTextField(){
    return fileNameText;
  }
  
  public JTextField getModTextField(){
    return modMarker;
  }
     

  /**
   * Creates new form TheFrame
   */
  public TheFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    mainTextArea = new javax.swing.JTextArea();
    jPanel2 = new javax.swing.JPanel();
    fileNameText = new javax.swing.JTextField();
    modMarker = new javax.swing.JTextField();
    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    open = new javax.swing.JMenuItem();
    New = new javax.swing.JMenuItem();
    Save = new javax.swing.JMenuItem();
    SaveAs = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    mainTextArea.setEditable(false);
    mainTextArea.setColumns(20);
    mainTextArea.setRows(5);
    mainTextArea.setMinimumSize(new java.awt.Dimension(0, 0));
    jScrollPane1.setViewportView(mainTextArea);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jPanel2.setLayout(new java.awt.BorderLayout());

    fileNameText.setEditable(false);
    fileNameText.setMinimumSize(new java.awt.Dimension(10, 100));
    fileNameText.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fileNameTextActionPerformed(evt);
      }
    });
    jPanel2.add(fileNameText, java.awt.BorderLayout.CENTER);

    modMarker.setEditable(false);
    modMarker.setColumns(2);
    modMarker.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    modMarker.setText("     ");
    modMarker.setMaximumSize(new java.awt.Dimension(2147483630, 2147483647));
    modMarker.setMinimumSize(new java.awt.Dimension(0, 0));
    modMarker.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        modMarkerActionPerformed(evt);
      }
    });
    jPanel2.add(modMarker, java.awt.BorderLayout.WEST);

    getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

    fileMenu.setText("File");

    open.setText("Open");
    open.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        openActionPerformed(evt);
      }
    });
    fileMenu.add(open);

    New.setText("New");
    fileMenu.add(New);

    Save.setText("Save");
    Save.setEnabled(false);
    fileMenu.add(Save);

    SaveAs.setText("Save As");
    SaveAs.setEnabled(false);
    fileMenu.add(SaveAs);

    menuBar.add(fileMenu);

    setJMenuBar(menuBar);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_openActionPerformed

  private void fileNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameTextActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_fileNameTextActionPerformed

  private void modMarkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modMarkerActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_modMarkerActionPerformed

 

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem New;
  private javax.swing.JMenuItem Save;
  private javax.swing.JMenuItem SaveAs;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JTextField fileNameText;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea mainTextArea;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JTextField modMarker;
  private javax.swing.JMenuItem open;
  // End of variables declaration//GEN-END:variables
}
